import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
const require = createRequire("C:/Users/徐振/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js");
const { chromium } = require("playwright");
const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", e => errors.push(e.message));
const out = path.resolve("tmp/ad-push-qa");
await fs.mkdir(out, { recursive: true });
const button = name => page.getByRole("button", { name, exact: true });
const dialog = name => page.getByRole("dialog", { name, exact: true });
const workspace = () => dialog("添加推送任务");
const shot = name => page.screenshot({ path: path.join(out, `${name}.png`) });
const openPush = async () => { await button("推送广告账户").click(); await workspace().waitFor(); };
const bottom = async () => { await page.locator(".ap-scroll").evaluate(el => { el.scrollTop = el.scrollHeight; }); };
const top = async () => { await page.locator(".ap-scroll").evaluate(el => { el.scrollTop = 0; }); };
const data = () => page.evaluate(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")));
const finish = async () => {
  await dialog("推送记录").waitFor();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")).records.filter(r => !r.id.startsWith("demo-")).every(r => r.status === "推送成功"));
  await button("关闭推送记录").click();
};
try {
  await page.goto(process.env.AD_TEST_URL || "http://localhost:3000/");
  await button("登录").click();
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
  await openPush();
  assert.equal(await workspace().getByRole("button", { name: "巨量广告", exact: true }).count(), 0);
  await shot("01-only-push");
  await button("全部账户").click();
  assert.equal(await page.getByRole("checkbox", { name: "轻氧服饰直营-千川账户", exact: true }).isDisabled(), true);
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await page.getByRole("checkbox", { name: "悦己珠宝直播间-千川账户", exact: true }).check();
  await bottom();
  await button("添加格式").click();
  await page.getByLabel("格式名称", { exact: true }).fill("视频编号命名");
  await page.getByLabel("自定义标题", { exact: true }).fill("{梦畅AIGC编号}_{视频标题}");
  await dialog("新增").getByRole("button", { name: "确定", exact: true }).click();
  await shot("02-push-settings");
  await workspace().getByRole("button", { name: "确定", exact: true }).click();
  await finish();
  assert.equal((await data()).records.filter(r => r.method === "push").length, 2);
  assert.ok((await data()).records.filter(r => r.method === "push").every(r => r.assetName.startsWith("fv1_")));
  await openPush();
  await button("全域推广").click();
  for (const target of ["直播全域", "商品全域", "直播乘方", "商品乘方"]) {
    await button(target).click();
    await button("选择计划（0）").click();
    const text = await dialog("已有计划添加视频").locator(".ap-table tbody").innerText();
    assert.match(text, target.startsWith("直播") ? /直播日常/ : /商品日常/);
    assert.doesNotMatch(text, target.startsWith("直播") ? /商品日常/ : /直播日常/);
    if (target === "直播全域") await shot("03-plan-picker");
    await dialog("已有计划添加视频").getByRole("checkbox", { name: /选择计划/ }).first().check();
    await dialog("已有计划添加视频").getByRole("button", { name: "确定", exact: true }).click();
  }
  await page.getByRole("radio", { name: "移除低数据视频", exact: true }).check();
  await shot("04-removal-conditions");
  await page.getByRole("radio", { name: "不移除", exact: true }).check();
  await bottom();
  await workspace().getByRole("button", { name: "确定", exact: true }).click();
  await button("确认提交").click();
  await finish();
  const appended = (await data()).records.find(r => r.method === "full_domain");
  assert.equal(appended.applied, true);
  assert.equal(appended.deliveryStatus, "投放中");
  await openPush();
  await button("全域推广").click();
  await button("商品全域").click();
  await page.getByRole("radio", { name: "批量创建全域计划", exact: true }).check();
  await shot("05-product-create");
  await button("选择账户").click();
  await dialog("选择账户").getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await dialog("选择账户").getByRole("button", { name: "确定", exact: true }).click();
  await page.getByLabel("抖音号", { exact: true }).selectOption("2881940182740113-dy1");
  await page.getByLabel("商品", { exact: true }).selectOption("2881940182740113-store1-p1");
  await page.getByLabel("预算", { exact: true }).fill("600");
  await page.getByLabel("ROI目标", { exact: true }).fill("2.5");
  await page.getByLabel("创意标题1", { exact: true }).fill("轻盈卸净，开启清爽日常");
  await page.getByLabel("计划名称", { exact: true }).fill("{创建日期}_{商品名称}");
  await bottom();
  await shot("06-create-footer");
  await button("开始计划搭建").click();
  await finish();
  const created = (await data()).records.find(r => r.snapshot.workbench?.operation === "create");
  assert.equal(created.planResult, "创建成功");
  assert.equal(created.deliveryStatus, "已暂停");
  assert.ok((await data()).accounts.find(a => a.id === created.accountId).catalog.plans.some(p => p.id === created.planId));
  await openPush();
  await button("全域推广").click();
  await button("商品乘方").click();
  await page.getByRole("radio", { name: "批量创建乘方计划", exact: true }).check();
  await shot("13-multiplier-create");
  await button("引用模板").click();
  await dialog("选择计划模板").getByRole("radio", { name: "千川日常销售", exact: true }).check();
  await shot("14-template-reference");
  await dialog("选择计划模板").getByRole("button", { name: "确定", exact: true }).click();
  assert.equal(await page.getByLabel("预算", { exact: true }).inputValue(), "300");
  await button("存为预设模板").click();
  await page.getByLabel("保存名称", { exact: true }).fill("商品乘方日常投放");
  await dialog("存为预设模板").getByRole("button", { name: "确定", exact: true }).click();
  await button("选择预设模板").click();
  assert.equal(await page.getByRole("option", { name: "商品乘方日常投放", exact: true }).count(), 1);
  await page.keyboard.press("Escape");
  await button("引用已有计划参数").click();
  await page.setViewportSize({ width: 390, height: 844 });
  await shot("15-plan-picker-mobile");
  assert.equal(await dialog("引用已有计划").evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await dialog("引用已有计划").getByRole("button", { name: "取消", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await top();
  await button("推送并搭建计划（单创意）").click();
  await page.getByRole("checkbox", { name: "选择模板 千川日常销售", exact: true }).check();
  await shot("07-single-template");
  await button("选择账户").click();
  await dialog("选择账户").getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await dialog("选择账户").getByRole("button", { name: "确定", exact: true }).click();
  await page.getByLabel("抖音号", { exact: true }).selectOption("2881940182740113-dy1");
  await page.getByLabel("商品", { exact: true }).selectOption("2881940182740113-store1-p1");
  await bottom();
  await workspace().getByRole("button", { name: "确定", exact: true }).click();
  await finish();
  await openPush();
  await button("推送并搭建计划（多创意）").click();
  await shot("08-multi-template");
  await bottom();
  await page.getByRole("radio", { name: "每个计划分配n个视频", exact: true }).check();
  assert.equal(await page.getByLabel("每计划视频数", { exact: true }).inputValue(), "1");
  await shot("09-multi-settings");
  await top();
  await page.setViewportSize({ width: 390, height: 844 });
  await shot("10-mobile");
  assert.equal(await workspace().evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await bottom();
  await button("推送成功后视频状态").click();
  const menu = page.locator(".ap-menu");
  await menu.waitFor();
  const bounds = await menu.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  await shot("11-mobile-popover");
  await page.keyboard.press("Escape");
  assert.equal(await menu.count(), 0);
  await page.setViewportSize({ width: 1920, height: 1080 });
  await top();
  await button("仅推送").click();
  await shot("12-wide");
  assert.deepEqual(errors, []);
  console.log("Passed: four modes, four targets/two plan categories, append/create, template plan, naming, record results, overlays and desktop/mobile layouts.");
} catch (e) {
  await shot("failure");
  console.error(await page.locator("body").innerText());
  throw e;
} finally { await browser.close(); }
