import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire("C:/Users/徐振/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js");
const { chromium } = require("playwright");
const browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(10000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const output = path.resolve("docs/previews/ad-push");
await fs.mkdir(output, { recursive: true });
const button = name => page.getByRole("button", { name, exact: true });
const dialog = name => page.getByRole("dialog", { name, exact: true });
const capture = name => page.screenshot({ path: path.join(output, `${name}.png`) });
const store = () => page.evaluate(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")));
const openVideo = async () => {
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
};
try {
  await page.goto(process.env.AD_TEST_URL || "http://127.0.0.1:3001/mengchang3/");
  await button("登录").click();
  await openVideo();
  await button("推送广告账户").click();
  await button("选择账户").click();
  assert.equal(await page.getByRole("checkbox", { name: "轻氧服饰直营-千川账户", exact: true }).isDisabled(), true);
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await page.getByRole("checkbox", { name: "悦己珠宝直播间-千川账户", exact: true }).check();
  await capture("account-picker-desktop");
  await dialog("选择账户").getByRole("button", { name: "确定", exact: true }).click();
  await button("提交推送").click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")).records.filter(r => r.method === "push").every(r => r.status === "推送成功"));
  assert.equal((await store()).records.filter(r => r.method === "push").length, 2);
  assert.equal(await page.evaluate(() => JSON.parse(sessionStorage.getItem("mengchang-resource-edits-v1-finished")).fv1.status), "已上机");
  await capture("records-desktop");
  await button("重新编辑").first().click();
  assert.equal(await page.getByLabel("抖音号", { exact: true }).inputValue(), "2881940182740113-dy1");
  await button("新建模板").click();
  await page.getByPlaceholder("请输入模板名称", { exact: true }).fill("验收模板");
  await page.getByPlaceholder("请选择词包", { exact: true }).fill("固定_");
  await button("下一步").click();
  await button("保存模板").click();
  assert.match(await dialog("计划模板配置").innerText(), /至少添加一个动态词包/);
  await button("上一步").click();
  await button("{日期(月日)}").click();
  await page.getByPlaceholder("请选择词包", { exact: true }).focus();
  await button("{视频作者}").click();
  assert.equal(await page.getByPlaceholder("请选择词包", { exact: true }).inputValue(), "固定_{日期(月日)}{视频作者}");
  assert.equal(await page.getByRole("radio", { name: "搜索广告", exact: true }).isDisabled(), true);
  await capture("template-desktop");
  await page.setViewportSize({ width: 390, height: 844 });
  await capture("template-mobile");
  assert.equal(await dialog("计划模板配置").evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await button("下一步").click();
  await button("保存模板").click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  assert.equal((await store()).templates.length, 2);
  await button("新增组合").click();
  const selects = page.getByLabel("抖音号", { exact: true });
  await selects.nth(1).selectOption("2881940182740113-dy2");
  await page.getByLabel("店铺", { exact: true }).nth(1).selectOption("2881940182740113-store1");
  await page.getByLabel("商品", { exact: true }).nth(1).selectOption("2881940182740113-store1-p1");
  await capture("plan-desktop");
  await button("提交推送").click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")).records.filter(r => !r.id.startsWith("demo-")).every(r => r.status === "推送成功"));
  assert.equal((await store()).records.filter(r => !r.id.startsWith("demo-") && r.method === "plan").length, 4);
  assert.ok((await store()).records.filter(r => !r.id.startsWith("demo-") && r.method === "plan").every(r => r.deliveryStatus === "已暂停"));
  await button("创建计划记录").click();
  await capture("plan-records-desktop");
  await button("关闭推送记录").click();
  await button("推送广告账户").click();
  await button("全域推广").click();
  await button("选择账户").click();
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await dialog("选择账户").getByRole("button", { name: "确定", exact: true }).click();
  await page.getByLabel("抖音号", { exact: true }).selectOption("2881940182740113-dy1");
  await page.getByLabel("已有全域计划", { exact: true }).selectOption({ index: 1 });
  await button("提交推送").click();
  await capture("full-domain-confirm");
  await button("确认追加").click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")).records.some(r => r.method === "full_domain" && r.applied));
  const appended = (await store()).accounts.find(a => a.id === "2881940182740113").catalog.plans[0];
  assert.deepEqual(appended.videoIds, ["existing-video", "fv1"]);
  assert.equal(appended.status, "投放中");
  await button("关闭推送记录").click();
  await button("推送广告账户").click();
  await button("推送并搭建计划").click();
  await button("删除模板 千川日常销售").click();
  await button("确定删除").click();
  await button("关闭推送任务").click();
  await button("查看推送记录").click();
  await button("重新编辑").first().click();
  assert.match(await dialog("添加推送任务").innerText(), /原模板已删除/);
  await page.getByRole("checkbox", { name: "选择模板 验收模板", exact: true }).check();
  await button("提交推送").click();
  await dialog("推送记录").waitFor();
  await button("详情").first().click();
  await capture("record-detail-desktop");
  await button("关闭推送任务详情").click();
  await button("关闭推送记录").click();
  await button("返回成片列表").click();
  await button("用户端").click();
  await button("管理端").click();
  await page.locator("#sidebar-item-system_management").click();
  await button("广告组管理").click();
  await button("巨量千川").click();
  await button("去授权").click();
  await button("前往授权").click();
  await page.getByRole("radio", { name: /梦畅官方店1/ }).check();
  await capture("authorization-desktop");
  await button("确认授权").click();
  await button("返回账户列表").click();
  assert.ok((await store()).accounts.find(a => a.id === "90000000000001"));
  await button("手动同步").click();
  await dialog("同步结果").waitFor();
  assert.match(await dialog("同步结果").innerText(), /失败 3 个/);
  await capture("sync-result-desktop");
  await button("关闭同步结果").click();
  await button("账户分组").click();
  await button("编辑").last().click();
  await capture("account-group-desktop");
  await page.setViewportSize({ width: 390, height: 844 });
  await capture("account-group-mobile");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await button("取消").last().click();
  await button("系统设置").click();
  await page.locator('input[name="ad-visibility"][value="personal"]').check();
  await button("保存账户可见性").click();
  assert.equal((await store()).visibility, "personal");
  await capture("visibility-settings-desktop");
  await page.locator('input[name="ad-visibility"][value="all"]').check();
  await button("保存账户可见性").click();
  await page.evaluate(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "putongyonghu", mode: "user" })));
  await page.reload();
  await openVideo();
  await button("推送广告账户").click();
  assert.match(await page.locator("body").innerText(), /暂无推送权限/);
  await page.evaluate(() => localStorage.setItem("cloud_video_roles_v2", JSON.stringify([{ id: "role_staff", enabled: true, checkedKeys: ["uc_ad_push"] }])));
  await button("推送广告账户").click();
  assert.equal(await button("推送并搭建计划").isDisabled(), true);
  await capture("permission-disabled-desktop");
  assert.deepEqual(errors, []);
  console.log("Browser checks passed: push, templates, full-domain append, authorization, synchronization, visibility, permission denial, desktop/mobile screenshots.");
} catch (error) {
  await capture("failure");
  console.error(await page.locator("body").innerText());
  throw error;
} finally {
  await browser.close();
}
