import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";
const { chromium } = createRequire(import.meta.url)("playwright");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
page.setDefaultTimeout(12000);
const screenshotDir = new URL("../docs/previews/ai-video-scenes/", import.meta.url);
await mkdir(screenshotDir, { recursive: true });
const { fileURLToPath } = await import("node:url");
const shot = (name) => page.screenshot({ path: fileURLToPath(new URL(`${name}.png`, screenshotDir)) });
const selectMode = async (name) => {
  await page.locator("aside").last().getByRole("button", { name: /^(参考生视频|首尾帧生视频|配音生视频|视频编辑|痛点对比|使用过程)$/ }).click();
  await page.getByRole("button", { name: new RegExp(`^${name} `) }).click();
};
const selectMaterial = async (label, type) => {
  await page.getByRole("button", { name: new RegExp(`^添加${label}`) }).click();
  if (type === "image" && label !== "商品图片") await page.getByRole("button", { name: "图片", exact: true }).click();
  const rows = page.locator("tbody tr");
  await rows.first().click();
  await page.getByRole("button", { name: "确认选择", exact: true }).click();
};
try {
  await page.routeWebSocket(/ws:\/\/localhost:3000\//, (socket) => socket.close());
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "putongyonghu", mode: "user" })));
  await page.goto("http://localhost:3000", { waitUntil: "domcontentloaded" });
  await page.getByRole("button", { name: "快速创作", exact: true }).click();
  assert.equal(await page.locator('option[value="痛点对比"], option[value="使用过程"]').count(), 0);
  assert.equal(await page.locator('option[value="产品素材"]').count(), 0);
  await page.getByRole("button", { name: "AI视频原料", exact: true }).click();
  await selectMode("痛点对比");
  const generate = page.getByRole("button", { name: /立即生成/ });
  assert.equal(await generate.isDisabled(), true);
  assert.equal(await page.locator("aside").last().locator("textarea").inputValue(), "");
  await selectMaterial("痛点素材", "image");
  assert.equal(await generate.isDisabled(), true);
  await selectMaterial("解决痛点素材", "video");
  assert.equal(await generate.isEnabled(), true);
  await shot("pain-config");
  await generate.click();
  const record = page.locator('article[id^="ai-video-record-ai-video-"]').filter({ hasText: /任务名称：AI视频原料_痛点对比_\d/ }).first();
  await record.getByText("排队中", { exact: true }).first().waitFor();
  await record.getByRole("heading", { name: "已为你生成 1 个视频", exact: true }).waitFor();
  assert.equal(await record.getByTitle("选择视频").count(), 1);
  await record.getByRole("button", { name: "重新编辑", exact: true }).click();
  assert.equal(await page.locator("aside").last().locator("textarea").inputValue(), "");
  assert.equal(await generate.isEnabled(), true);
  await record.getByTitle("选择视频").click();
  await record.getByRole("button", { name: /上传资源库/ }).click();
  await page.getByText("视频上传页面", { exact: true }).waitFor();
  assert.equal(await page.getByRole("heading", { name: "痛点对比工作台", exact: true }).count(), 0);
  await shot("publish");
  await page.getByRole("button", { name: /返回/ }).first().click();
  await page.getByRole("heading", { name: "痛点对比工作台", exact: true }).waitFor();
  await selectMode("使用过程");
  assert.equal(await generate.isDisabled(), true);
  await selectMaterial("使用过程视频", "video");
  await selectMaterial("商品图片", "image");
  const prompt = page.locator("aside").last().locator("textarea");
  await prompt.fill("展示使用步骤与商品细节");
  await generate.click();
  const usageRecord = page.locator('article[id^="ai-video-record-ai-video-"]').filter({ hasText: /任务名称：AI视频原料_使用过程_\d/ }).first();
  await usageRecord.getByRole("button", { name: "取消排队", exact: true }).click();
  await usageRecord.getByText("积分已退还，点击重新编辑可再次提交", { exact: true }).waitFor();
  await prompt.fill("新草稿");
  await usageRecord.getByRole("button", { name: "重新编辑", exact: true }).click();
  assert.equal(await prompt.inputValue(), "展示使用步骤与商品细节");
  await page.locator("aside").last().getByRole("button", { name: "星绘 Pro", exact: true }).click();
  await page.getByRole("button", { name: /云镜 Max 视频 60/ }).click();
  await page.getByRole("button", { name: /9:16/ }).first().click();
  assert.equal(await page.getByRole("slider").getAttribute("max"), "30");
  await page.keyboard.press("Escape");
  await shot("usage-config");
  await generate.click();
  await usageRecord.getByRole("heading", { name: "已为你生成 1 个视频", exact: true }).waitFor();
  await usageRecord.locator('button[title^="预览 "]').click();
  assert.equal(await page.locator("video[controls]").count(), 1);
  await page.getByTitle("关闭", { exact: true }).click();
  const taskName = await usageRecord.locator('button[title^="预览 "]').getAttribute("title");
  await page.getByRole("button", { name: "快速创作", exact: true }).click();
  await page.getByTitle(/^当前有 /).click();
  const queue = page.getByRole("complementary").filter({ has: page.getByRole("heading", { name: "任务队列", exact: true }) });
  await queue.getByRole("button", { name: "全部任务", exact: true }).first().click();
  await queue.getByRole("button", { name: "AI视频原料", exact: true }).click();
  await queue.locator("article").filter({ hasText: taskName.replace(/^预览 /, "").replace(/\.mp4$/, "") }).filter({ hasText: "生成成功" }).first().click();
  await page.getByRole("heading", { name: "使用过程工作台", exact: true }).waitFor();
  await usageRecord.waitFor();
  assert.ok((await usageRecord.getAttribute("class")).includes("border-violet-500"));
  console.log(JSON.stringify({ status: "passed", errors, screenshots: fileURLToPath(screenshotDir) }));
  assert.deepEqual(errors, []);
} catch (error) {
  console.error((await page.locator("body").innerText()).slice(-6000));
  await shot("failure");
  throw error;
} finally {
  await browser.close();
}
