import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const dialog = name => page.getByRole("dialog", { name, exact: true });
const tab = name => page.getByRole("tab", { name, exact: true });
const row = status => page.getByTestId(`derivation-row-${status}`);
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await page.locator("#sidebar-item-operation_records").click();
  await expect(page.getByRole("tab")).toHaveCount(6);
  await expect(page.getByTestId("derivation-history").locator("tbody tr")).toHaveCount(6);
  await expect(page.getByLabel("衍生状态").locator("option")).toHaveText(["全部状态", "成功", "失败", "处理中", "取消衍生", "待衍生", "已删除"]);
  await expect(page.getByTestId("derivation-history")).not.toContainText("衍生方式");
  await page.screenshot({ path: "tmp/operation-records-desktop.png" });
  await row("成功").getByRole("button", { name: "预览", exact: true }).click();
  await expect(page.locator('[role="dialog"] video')).toBeVisible();
  await expect.poll(() => page.locator('[role="dialog"] video').evaluate(v => v.readyState)).toBeGreaterThan(1);
  await page.locator('[role="dialog"]').getByRole("button", { name: /^关闭/ }).click();
  await row("成功").getByRole("checkbox").check();
  await expect(button("批量下载")).toBeEnabled();
  await expect(button("批量取消")).toBeDisabled();
  await button("批量备注").click();
  await page.getByLabel("记录备注").fill("九月护肤投放 / 第一轮");
  await dialog("修改备注").getByRole("button", { name: "确认", exact: true }).click();
  await expect(row("成功")).toContainText("九月护肤投放 / 第一轮");
  const download = page.waitForEvent("download");
  await row("成功").getByRole("button", { name: "下载", exact: true }).click();
  await download;
  await tab("下载记录").click();
  await expect(page.locator("tbody tr").first()).toContainText("衍生视频");
  await expect(page.locator("tbody tr").first()).toContainText("已发起");
  await tab("衍生视频记录").click();
  await row("待衍生").getByRole("checkbox").check();
  await button("批量取消").click();
  await dialog("取消衍生").getByRole("button", { name: "确认", exact: true }).click();
  await expect(row("待衍生")).toHaveCount(0);
  await expect(row("取消衍生")).toHaveCount(2);
  await row("失败").getByRole("checkbox").check();
  await button("批量重试").click();
  await dialog("重试衍生").getByRole("button", { name: "确认", exact: true }).click();
  await expect(row("待衍生")).toHaveCount(1);
  await expect(row("成功")).toHaveCount(2, { timeout: 10000 });
  await page.getByLabel("视频标题", { exact: true }).fill("不存在的成片");
  await button("查询").click();
  await expect(page.getByText("暂无数据", { exact: true })).toBeVisible();
  await button("重置").click();
  await row("成功").getByRole("checkbox").first().check();
  await row("成功").getByRole("checkbox").last().check();
  await button("批量推送").click();
  await expect(page.getByTestId("ad-derivation-options")).toHaveCount(0);
  await button("全部账户").click();
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await dialog("添加推送任务").getByRole("button", { name: "确定", exact: true }).click();
  await expect(tab("推送视频记录")).toHaveAttribute("aria-selected", "true");
  await expect(page.getByText("已提交 2 条推送记录", { exact: true })).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(4);
  await tab("衍生视频记录").click();
  await expect(page.locator("tbody tr")).toHaveCount(6);
  await expect(page.getByRole("button", { name: "2 条推送记录", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "2 条推送记录", exact: true }).click();
  await expect(dialog("推送记录").locator("tbody tr")).toHaveCount(2);
  await dialog("推送记录").getByRole("button", { name: /^关闭/ }).click();
  const csv = page.waitForEvent("download");
  await button("导出").click(); await csv;
  await tab("导出记录").click();
  await expect(page.locator("tbody tr").first()).toContainText("衍生视频记录.csv");
  const redownload = page.waitForEvent("download");
  await page.locator("tbody tr").first().getByRole("button", { name: "下载", exact: true }).click(); await redownload;
  await tab("上传文件记录").click();
  await expect(page.locator("tbody tr")).toHaveCount(7);
  await page.getByLabel("记录类型").selectOption("第三方");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await button("详情").click(); await expect(dialog("记录详情")).toContainText("轻氧跑鞋");
  await dialog("记录详情").getByRole("button", { name: /^关闭/ }).click();
  await tab("登录记录").click(); await expect(page.locator("tbody tr")).toHaveCount(2);
  await tab("衍生视频记录").click();
  await page.setViewportSize({ width: 768, height: 900 });
  await page.screenshot({ path: "tmp/operation-records-tablet.png" });
  assert.ok(await page.getByTestId("operation-records").evaluate(el => el.scrollWidth <= el.clientWidth));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator("aside button").last().click();
  await expect.poll(() => page.locator("aside").evaluate(el => el.getBoundingClientRect().width)).toBeLessThanOrEqual(65);
  await page.screenshot({ path: "tmp/operation-records-mobile.png" });
  assert.ok(await page.getByTestId("operation-records").evaluate(el => el.scrollWidth <= el.clientWidth));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator("aside button").last().click();
  await expect.poll(() => page.locator("aside").evaluate(el => el.getBoundingClientRect().width)).toBeGreaterThanOrEqual(255);
  // Inject another user's operations without a reload, then ensure every tab stays scoped.
  await page.evaluate(async () => {
    const history = await import("/src/lib/operationHistory.ts");
    history.recordOperation({ ownerId: "other-user", kind: "upload", name: "OTHER-PRIVATE-FILE", type: "成片", status: "成功", message: "" });
    const derivation = await import("/src/lib/videoDerivation.ts");
    derivation.seedDerivationExamples("other-user");
  });
  await expect(page.locator("tbody tr")).toHaveCount(6);
  await row("成功").first().getByRole("button", { name: "删除", exact: true }).click();
  await dialog("删除衍生视频").getByRole("button", { name: "确认", exact: true }).click();
  await expect(row("已删除")).toHaveCount(2);
  await tab("上传文件记录").click();
  await expect(page.getByText("OTHER-PRIVATE-FILE")).toHaveCount(0);
  await expect(page.locator("tbody tr")).toHaveCount(7);
  assert.deepEqual(errors, []);
  console.log("PASS operation records: six tabs, states, media preview, cancel/retry, batch push without re-derivation, linked push records, exports/downloads, owner isolation, desktop/mobile layout");
} catch (error) { await page.screenshot({ path: "tmp/operation-records-failure.png" }); throw error; }
finally { await browser.close(); }
