import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
page.on("dialog", dialog => dialog.accept());
const button = name => page.getByRole("button", { name, exact: true });
const switchMode = async name => { await page.locator("#btn-client-mode-dropdown").click(); await button(name).click(); };
const cards = () => page.getByTestId("material-video-card");
const adminCards = () => page.getByTestId("admin-resource-card");
const firstThird = () => page.locator('[data-testid="admin-resource-card"][data-resource-id="third-party-1"]');
const openUser = async () => { await switchMode("用户端"); await page.locator("#sidebar-item-resources").click(); await button("第三方管理").click(); };
const openAdmin = async () => { await switchMode("管理端"); await page.locator("#sidebar-item-content_management").click(); await button("第三方").click(); };
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await page.locator("#sidebar-item-resources").click();
  await button("第三方管理").click();
  await expect(cards()).toHaveCount(6);
  await cards().first().click();
  await button("更多").click();
  await expect(button("衍生新视频")).toHaveCount(0);
  await button("删除").click();
  await expect(cards()).toHaveCount(5);
  await openAdmin();
  await expect(adminCards()).toHaveCount(5);
  await button("回收站").click();
  await expect(firstThird()).toContainText("用户端");
  await page.screenshot({ path: "tmp/third-party-trash.png" });
  await firstThird().getByRole("button", { name: "恢复", exact: true }).click();
  await button("第三方").click();
  await expect(adminCards()).toHaveCount(6);
  await firstThird().click();
  await expect(button("推送广告账户")).toHaveCount(0);
  await expect(page.getByText("第三方区", { exact: true })).toBeVisible();
  await page.screenshot({ path: "tmp/third-party-admin-detail.png" });
  await button("返回第三方列表").click();
  await openUser();
  await expect(cards()).toHaveCount(6);
  await button("上传文件").click();
  await page.getByRole("button", { name: /^上传视频/ }).click();
  await expect(page.getByRole("radio", { name: "第三方", exact: true })).toBeChecked();
  await page.getByRole("combobox", { name: "资源分类", exact: true }).click();
  const popup = page.locator('[data-overlay-layer="popover"]').last();
  await popup.getByText("美妆", { exact: true }).click();
  await popup.getByText("特写质感镜头", { exact: true }).click();
  await page.locator('input[type="file"]').first().setInputFiles("public/assets/viral-gallery/serum.mp4");
  await button("发布").click();
  await expect(cards()).toHaveCount(7);
  await openAdmin();
  await expect(adminCards()).toHaveCount(7);
  await expect(adminCards().filter({ hasText: "serum.mp4" })).toHaveCount(1);
  await firstThird().getByRole("button", { name: "删除", exact: true }).click();
  await page.getByRole("dialog", { name: "删除资源", exact: true }).getByRole("button", { name: "确认删除", exact: true }).click();
  await expect(adminCards()).toHaveCount(6);
  await button("回收站").click();
  await firstThird().getByRole("button", { name: "彻底删除", exact: true }).click();
  await page.getByRole("dialog", { name: "彻底删除资源", exact: true }).getByRole("button", { name: "确定", exact: true }).click();
  await expect(firstThird()).toHaveCount(0);
  await openUser();
  await expect(cards()).toHaveCount(6);
  await expect(page.getByText("0920-精华液质地展示-品牌供片.mp4", { exact: true })).toHaveCount(0);
  assert.deepEqual(errors, []);
  console.log("PASS: user/admin shared third-party list, detail, upload, trash, restore and permanent deletion");
} catch (error) {
  await page.screenshot({ path: "tmp/third-party-admin-failure.png" });
  throw error;
} finally { await browser.close(); }
