import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const cards = () => page.getByTestId("material-video-card");
const switchMode = async name => {
  await page.locator("#btn-client-mode-dropdown").click();
  await button(name).click();
};
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await page.locator("#sidebar-item-resources").click();
  await button("素材管理").click();
  const materialLayout = await page.getByTestId("material-resource-view").getAttribute("class");
  await page.screenshot({ path: "tmp/materials-reference.png" });
  await button("第三方管理").click();
  await expect(cards()).toHaveCount(6);
  assert.equal(await page.getByTestId("material-resource-view").getAttribute("class"), materialLayout);
  await expect(page.getByTestId("material-resource-view")).toHaveAttribute("data-resource-scope", "thirdParty");
  await expect.poll(() => cards().locator("img").evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: "tmp/third-party-desktop.png" });
  await cards().first().hover();
  await expect.poll(() => cards().first().locator("video").evaluate(v => v.readyState >= 2)).toBe(true);
  await cards().first().click();
  await expect(button("返回第三方列表")).toBeVisible();
  await expect(page.getByText("第三方区", { exact: true })).toBeVisible();
  await expect(button("推送广告账户")).toHaveCount(0);
  await page.screenshot({ path: "tmp/third-party-detail.png" });
  await button("返回第三方列表").click();
  await page.getByTestId("thirdParty-primary-filter").getByRole("button", { name: "美妆", exact: true }).click();
  await expect(cards()).toHaveCount(2);
  await page.getByTestId("thirdParty-secondary-filter").getByRole("button", { name: "特写质感镜头", exact: true }).click();
  await expect(cards()).toHaveCount(1);
  await button("重置").click();
  await expect(cards()).toHaveCount(6);
  await button("选择").click();
  await cards().first().getByTitle("选择此项", { exact: true }).click();
  await button("修改").click();
  await page.getByRole("menuitem", { name: "修改状态", exact: true }).click();
  const statusDialog = page.getByRole("dialog", { name: "修改状态", exact: true });
  await statusDialog.getByRole("combobox").selectOption("画面利用");
  await statusDialog.getByRole("button", { name: "确定", exact: true }).click();
  await expect(cards().first()).toContainText("画面利用");
  await button("素材管理").click();
  await expect(page.getByTestId("material-resource-view")).toHaveAttribute("data-resource-scope", "materials");
  await expect(page.getByText("0920-精华液质地展示-品牌供片.mp4", { exact: true })).toHaveCount(0);
  await button("第三方管理").click();
  await expect(cards().first()).toContainText("画面利用");
  await switchMode("管理端");
  await button("分类管理").click();
  const root = page.getByTestId("category-management");
  await root.getByRole("button", { name: "第三方", exact: true }).click();
  const parent = root.locator('[data-category-id="third-mat-c1"]');
  await parent.click();
  await parent.getByTitle("删除分类").click();
  await expect(page.getByRole("status")).toContainText("存在资源");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const child = root.locator('[data-category-id="third-mat-c1-3"]');
  await child.getByTitle("删除分类").click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await child.getByTitle("编辑名称").click();
  const edit = page.getByRole("dialog").last();
  await edit.getByRole("textbox").fill("品牌质地特写");
  await edit.getByRole("button", { name: "确定", exact: true }).click();
  await page.screenshot({ path: "tmp/third-party-admin.png" });
  await root.getByRole("button", { name: "素材", exact: true }).click();
  await expect(root.getByText("特写质感镜头", { exact: true })).toBeVisible();
  await expect(root.getByText("品牌质地特写", { exact: true })).toHaveCount(0);
  await switchMode("用户端");
  await page.locator("#sidebar-item-resources").click();
  await button("第三方管理").click();
  await expect(page.getByTestId("thirdParty-secondary-filter").getByRole("button", { name: "品牌质地特写", exact: true })).toBeVisible();
  await button("上传文件").click();
  await page.getByRole("button", { name: /^上传视频/ }).click();
  await expect(page.getByRole("radio", { name: "第三方", exact: true })).toBeChecked();
  await expect(page.getByLabel("拍摄时间", { exact: true })).toBeVisible();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const category = page.getByRole("combobox", { name: "资源分类", exact: true });
  await category.click();
  const popup = page.locator('[data-overlay-layer="popover"]').last();
  await popup.getByText("美妆", { exact: true }).click();
  await popup.getByText("品牌质地特写", { exact: true }).click();
  await page.locator('input[type="file"]').first().setInputFiles("public/assets/viral-gallery/serum.mp4");
  await page.screenshot({ path: "tmp/third-party-upload.png" });
  await button("发布").click();
  await expect(cards()).toHaveCount(7);
  await expect(cards().first()).toContainText("serum.mp4");
  await cards().first().click();
  await expect(page.getByText("美妆 / 品牌质地特写", { exact: true })).toBeVisible();
  await button("返回第三方列表").click();
  await button("素材管理").click();
  await expect(page.getByText("serum.mp4", { exact: true })).toHaveCount(0);
  await button("第三方管理").click();
  await expect(cards()).toHaveCount(7);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(cards().first()).toBeVisible();
  await page.screenshot({ path: "tmp/third-party-mobile.png" });
  assert.deepEqual(errors, []);
  console.log("PASS: material layout reuse, local media, detail, filters, scoped edits, admin category isolation/deletion guard, upload routing and mobile render");
} catch (error) {
  await page.screenshot({ path: "tmp/third-party-failure.png" });
  throw error;
} finally {
  await browser.close();
}
