import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const dialog = name => page.getByRole("dialog", { name, exact: true });
const switchMode = async name => { await page.locator("#btn-client-mode-dropdown").click(); await button(name).click(); };
const openFinished = async () => {
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
};
const moreAction = async name => { await button("更多").click(); await button(name).click(); };
const bottom = () => page.locator(".ap-scroll").evaluate(el => { el.scrollTop = el.scrollHeight; });
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await switchMode("管理端");
  await page.locator("#sidebar-item-system_management").click();
  await expect(page.getByRole("checkbox", { name: "第三方管理", exact: true })).toBeChecked();
  await expect(page.getByRole("checkbox", { name: "第三方管理", exact: true })).toBeDisabled();
  await button("系统设置").click();
  const limit = page.getByLabel("每个员工，可同时衍生视频数量上限", { exact: true });
  await limit.fill("4");
  const section = limit.locator("xpath=ancestor::div[.//button[normalize-space()='保存设置']][1]");
  await section.getByRole("button", { name: "保存设置", exact: true }).click();
  await expect.poll(() => page.evaluate(() => JSON.parse(sessionStorage.getItem("mengchang-ad-push-settings")).maxDerive)).toBe(4);
  await switchMode("用户端");
  await openFinished();
  await moreAction("衍生新视频");
  const derive = dialog("衍生新视频");
  await expect(derive).toContainText("本次最多可衍生 4 个");
  const count = derive.getByRole("spinbutton");
  for (const invalid of ["0", "1.5", "5"]) {
    await count.fill(invalid);
    await expect(derive.getByRole("button", { name: "确定", exact: true })).toBeDisabled();
  }
  await count.fill("2");
  await page.screenshot({ path: "tmp/derive-dialog-desktop.png" });
  await button("衍生说明").hover();
  await expect(page.locator('[data-overlay-layer="popover"]').last()).toContainText("梦畅AIGC平台");
  await page.mouse.move(0, 0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "tmp/derive-dialog-mobile.png" });
  assert.equal(await derive.locator(":scope > div").evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await derive.getByRole("button", { name: "确定", exact: true }).click();
  await expect(page.getByText("已提交 2 个视频的衍生任务", { exact: true })).toBeVisible();
  await moreAction("衍生新视频");
  await expect(derive).toContainText("本次最多可衍生 2 个");
  await derive.getByRole("button", { name: "取消", exact: true }).click();
  await expect(page.getByText("衍生处理已完成，共 2 个视频", { exact: true })).toBeVisible({ timeout: 10000 });
  await expect(page.getByText("衍生处理已完成，共 2 个视频", { exact: true })).toHaveCount(0, { timeout: 8000 });
  await button("推送广告账户").click();
  await expect(page.getByTestId("ad-derivation-options")).toHaveCount(0);
  await button("关闭推送任务").click();
  await moreAction("衍生视频并推送");
  const workspace = dialog("添加推送任务");
  await expect(page.getByTestId("ad-derivation-options")).toHaveCount(1);
  await expect(workspace.getByText("衍生方式", { exact: true })).toHaveCount(0);
  await expect(workspace.getByText("本地衍生", { exact: true })).toHaveCount(0);
  await expect(page.getByTestId("ad-derivation-options")).toContainText("本地衍生上限 4 个");
  await expect(workspace).not.toContainText("云端衍生");
  await expect(workspace).not.toContainText("未开通");
  await button("全部账户").click();
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await page.getByRole("checkbox", { name: "悦己珠宝直播间-千川账户", exact: true }).check();
  await bottom();
  await page.getByLabel("每个广告账户衍生数量", { exact: true }).fill("3");
  await workspace.getByRole("button", { name: "确定", exact: true }).click();
  await expect(workspace.getByRole("alert")).toContainText("最多可衍生 4");
  await page.getByLabel("每个广告账户衍生数量", { exact: true }).fill("");
  await page.getByRole("radio", { name: "只衍生1个视频", exact: true }).check();
  await expect(page.getByTestId("ad-derivation-options")).toContainText("预计衍生 1 个新视频");
  await page.getByRole("radio", { name: "每个广告账户衍生N个", exact: true }).check();
  await page.getByLabel("每个广告账户衍生数量", { exact: true }).fill("2");
  await expect(page.getByTestId("ad-derivation-options")).toContainText("预计衍生 4 个新视频");
  await page.screenshot({ path: "tmp/derive-push-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await bottom();
  await page.screenshot({ path: "tmp/derive-push-mobile.png" });
  assert.equal(await workspace.evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await workspace.getByRole("button", { name: "确定", exact: true }).click();
  await dialog("推送记录").waitFor();
  await expect(dialog("推送记录").locator("tbody").getByText("衍生中", { exact: true }).first()).toBeVisible();
  await page.waitForFunction(() => {
    const rows = JSON.parse(localStorage.getItem("mengchang-ad-workflow-v2")).records.filter(r => r.derivativeId);
    return rows.length === 4 && rows.every(r => r.status === "推送成功");
  });
  await dialog("推送记录").getByLabel("推送视频类型").selectOption("衍生视频");
  await expect(dialog("推送记录").locator("tbody tr")).toHaveCount(4);
  await dialog("推送记录").getByRole("button", { name: "详情", exact: true }).first().click();
  await expect(dialog("推送任务详情")).not.toContainText("衍生方式");
  await expect(dialog("推送任务详情")).toContainText("衍生编号");
  await page.screenshot({ path: "tmp/derive-push-result.png" });
  assert.deepEqual(errors, []);
  console.log("PASS: admin quota, read-only permissions, standalone submit/completion, no cloud option, ordinary push unchanged, derived push counts/results and desktop/mobile overlays");
} catch (error) {
  await page.screenshot({ path: "tmp/derive-failure.png" });
  throw error;
} finally { await browser.close(); }
